language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
node_js: "10"
install: echo "install happens as part of setup"
script: npm run setup
branches:
  only: master